# Use postgres/example user/password credentials
version: '3.1'

services:

  jukebox:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jukebox
      POSTGRES_DB: jukebox
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql
      - ./db/scripts:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
